import "@/styles/global.css";
import Nav from "@/components/navbar/Nav";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";

import ToasterProvider from "./providers/ToasterProvider";

import RegisterModal from "@/components/modals/RegisterModal";
import { ThemeProvider } from "./providers/ThemeProvider";
import LoginModal from "@/components/modals/LoginModal";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({ children, authModal }: { children: React.ReactNode; authModal: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        suppressHydrationWarning={true}
        className={cn(
          `min-h-screen scroll-smooth
        bg-background
        pt-12 
        font-sans text-foreground antialiased`,
          inter.className
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ToasterProvider />
          <LoginModal />
          <RegisterModal />
          {authModal}

          <Nav />

          <div className="container mx-auto h-full max-w-7xl pt-12">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
